import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Script from "next/script";


const exo = Exo({ 
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  variable: '--font-exo'
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Load Monnify SDK */}
        <Script
          src="https://sdk.monnify.com/plugin/monnify.js"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`${exo.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
