import type { Metadata } from "next";
import { Bebas_Neue, Sora } from "next/font/google";
import "./globals.css";
import Script from "next/script";


const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

const sora = Sora({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-sora",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Load Monnify SDK */}
        <Script
          src="https://sdk.monnify.com/plugin/monnify.js"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`${bebas.variable} ${sora.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
